name: Terraform Apply (OIDC)

on:
  push:
    branches: ["main"]
    paths:
      - "INFRA/**"
      - ".github/workflows/terraform.yml"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: INFRA

    env:
      TF_IN_AUTOMATION: "true"
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_key_pair_name: ${{ secrets.KEY_PAIR_NAME }}
      TF_VAR_ssh_cidr: ${{ secrets.SSH_CIDR }}
      TF_VAR_custom_ami_id: ${{ secrets.CUSTOM_AMI_ID }}
      TF_VAR_github_deploy_pubkey: ${{ secrets.DEPLOY_PUBLIC_KEY }}
      # Optional: set these if you want to control them from CI
      # TF_VAR_project_name: nginx-ssh-deploy
      # TF_VAR_instance_type: t3.micro

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false -no-color

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -lock-timeout=2m

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -no-color -lock-timeout=2m
